version: "2.4"
services:
  nginx:
    build:
      context: .
      dockerfile: nginx.dockerfile
    networks:
      - tor-network
    ports:
      - "8118:8118"
      - "8119:8119"
      - "8080:80"
    links:
      - tor0
      - tor1
      - tor2
      - tor3
      - tor4
      - tor5
      - tor6
      - tor7
      - tor8
      - tor9
  tor0:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor1:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor2:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor3:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor4:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor5:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor6:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor7:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor8:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"
  tor9:
    image: dperson/torproxy
    networks:
      - tor-network
    expose:
      - "8118"

networks:
  tor-network:
